### ISSUE TITLE
在webpack@1.X下工作正常，但是在webpack@2.X下会出现编译多次的情况

### ISSUE THREAD

**Issue by asd123freedom** [jinzhubaofu/san-markdown-loader#1]
在webpack@2.X下，大概率会出现引起webpack编译两次，这两次的hash都是一致的，少数情况甚至会编译三次。通过删除代码二分法，最终确定是import  .md文件引发的这个问题

**Comment by asd123freedom** [comment]
本地的webpack版本是2.7

**Comment by jinzhubaofu** [comment]
原因应该是 san-markdown-loader 会把 codeblock 当作一个文件提取出来放到本地，触发了 webpack 的 watch 功能

可以通过添加 webpack 的配置来忽略这些临时文件

```js
module.exports = {
  plugins: [
    new webpack.WatchIgnorePlugin([
       /\.cache/
    ])
  ]
}
```

**Comment by jinzhubaofu** [comment]
在 readme 里边添加了指南，看看是否解决问题
